# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Default overrides
defaults:
  image_registry: ""
  image_tag: '{{ .Chart.AppVersion }}'
  image_org: "voltha/"
  image_pullPolicy: "Always"

# Define connectivity to required services
services:
  kafka:
    adapter:
      service: voltha-kafka.voltha.svc.cluster.local
      port: 9092
    cluster:
      service: voltha-kafka.voltha.svc.cluster.local
      port: 9092
  
  # Define connectivity to etcd
  etcd:
    service: voltha-etcd-cluster-client.voltha.svc.cluster.local
    port: 2379

# Define the recplica count for everything
replicas:
  adapter_open_olt: 1

images:
  adapter_open_olt:
    registry: '{{ .Values.defaults.image_registry }}'
    repository: '{{ .Values.defaults.image_org }}voltha-openolt-adapter'
    tag: '{{ .Values.defaults.image_tag }}'
    pullPolicy: '{{ .Values.defaults.image_pullPolicy | default "Always" }}'
